"use client";

import { Activity, Bot, CircleAlert, Clock3, DatabaseZap, MessageSquareText, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

type Stats = { conversations: number; messagesToday: number; activeUsers: number; newUsers: number; aiRequests: number; aiFailures: number; averageLatency: number; knowledgeStatus: string; lastSync: string | null; pagesIndexed?: number; chunksIndexed?: number };
const empty: Stats = { conversations: 0, messagesToday: 0, activeUsers: 0, newUsers: 0, aiRequests: 0, aiFailures: 0, averageLatency: 0, knowledgeStatus: "Loading", lastSync: null };
export function AdminDashboard() {
  const [stats, setStats] = useState(empty); const [configured, setConfigured] = useState(true);
  useEffect(() => { void fetch("/api/admin/stats", { cache: "no-store" }).then(async (response) => { if (response.ok) { const payload = await response.json() as { stats: Stats; configured: boolean }; setStats(payload.stats); setConfigured(payload.configured); } }); }, []);
  const cards = [["Total conversations", stats.conversations, MessageSquareText], ["Messages today", stats.messagesToday, Activity], ["Active users", stats.activeUsers, UsersRound], ["New users", stats.newUsers, UsersRound], ["AI requests", stats.aiRequests, Bot], ["AI failures", stats.aiFailures, CircleAlert], ["Avg response", `${stats.averageLatency} ms`, Clock3], ["Knowledge", stats.knowledgeStatus, DatabaseZap]] as const;
  return <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--cabi-primary)]">Command center</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Cabi at a glance</h1><p className="mt-2 text-sm text-[var(--cabi-text-muted)]">Conversation health, AI activity, and knowledge status.</p>{!configured && <div className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[0.05] p-4 text-sm text-amber-100">Supabase is not connected. The interface is ready, but live metrics and saved configuration will appear after setup.</div>}<div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface-1)] p-4"><div className="flex items-center justify-between"><p className="text-xs text-[var(--cabi-text-muted)]">{label}</p><Icon size={16} className="text-[var(--cabi-primary)]" /></div><p className="mt-4 truncate text-2xl font-semibold tracking-[-.03em]">{value}</p></div>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface)] p-5"><h2 className="text-sm font-semibold">AI reliability</h2><div className="mt-6 flex h-32 items-end gap-2" aria-label="AI request activity">{[42,64,51,78,70,89,83,91,68,76,94,86].map((height, index) => <span key={index} className="flex-1 rounded-t-md bg-gradient-to-t from-violet-500/20 to-violet-300/70" style={{ height: `${Math.max(8, stats.aiRequests ? height : 8)}%` }} />)}</div><div className="mt-2 flex justify-between text-[10px] text-[var(--cabi-text-faint)]"><span>Earlier</span><span>Now</span></div></div><div className="rounded-2xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface)] p-5"><h2 className="text-sm font-semibold">Knowledge base</h2><p className="mt-5 text-3xl font-semibold text-[var(--cabi-primary)]">{stats.chunksIndexed ?? 0}</p><p className="mt-1 text-xs text-[var(--cabi-text-muted)]">indexed chunks across {stats.pagesIndexed ?? 0} pages</p><p className="mt-6 text-xs text-[var(--cabi-text-muted)]">{stats.lastSync ? `Last synced ${new Date(stats.lastSync).toLocaleString()}` : "No Clank.trade sync yet"}</p></div></div></div>;
}
