"use client";

import { MiniCabi } from "@/components/cabi/mini-cabi";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function AdminLoginForm() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const payload = await response.json().catch(() => ({})) as { error?: string }; setBusy(false); if (!response.ok) { setError(payload.error ?? "Sign-in failed."); return; } router.replace("/admin"); router.refresh(); };
  return <main className="relative grid min-h-[100dvh] place-items-center overflow-hidden bg-[var(--cabi-bg)] p-4 text-white"><div className="absolute left-1/2 top-1/3 h-[480px] w-[480px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-500/[0.11] blur-[100px]" /><Link href="/" className="focus-ring absolute left-5 top-5 flex h-11 items-center gap-2 rounded-xl px-3 text-sm text-[var(--cabi-text-muted)] hover:bg-[var(--cabi-surface-2)] hover:text-white"><ArrowLeft size={17} /> Back to Cabi</Link><form onSubmit={submit} className="glass relative w-full max-w-[420px] rounded-2xl p-6 sm:p-8"><MiniCabi className="h-12 w-14" /><div className="mt-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.15em] text-[var(--cabi-primary)]"><LockKeyhole size={14} /> Secure admin</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Welcome back.</h1><p className="mt-2 text-sm leading-6 text-[var(--cabi-text-muted)]">Manage Cabi&apos;s AI, knowledge, and product settings.</p><label className="mt-7 block text-xs font-medium text-[var(--cabi-text-secondary)]">Email<input type="email" autoComplete="username" value={email} onChange={(event) => setEmail(event.target.value)} required className="mt-2 h-12 w-full rounded-xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface-2)] px-3 text-sm text-white outline-none focus:border-violet-300/35" /></label><label className="mt-4 block text-xs font-medium text-[var(--cabi-text-secondary)]">Password<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required className="mt-2 h-12 w-full rounded-xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface-2)] px-3 text-sm text-white outline-none focus:border-violet-300/35" /></label>{error && <p role="alert" className="mt-4 rounded-xl border border-rose-300/15 bg-rose-300/[0.05] p-3 text-xs text-rose-200">{error}</p>}<button disabled={busy} className="focus-ring mt-5 h-12 w-full rounded-xl bg-gradient-to-r from-violet-200 to-violet-400 text-sm font-semibold text-[var(--cabi-on-primary)] disabled:opacity-50">{busy ? "Checking…" : "Sign in"}</button></form></main>;
}
