"use client";

import { Header, Banner } from "@/components/admin/ai-settings-panel";
import { RotateCcw, Save } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

export type ConfigField = { key: string; label: string; kind?: "text" | "textarea" | "color" | "url" | "boolean"; help?: string };
export function ConfigPanel({ configKey, eyebrow, title, description, fields }: { configKey: string; eyebrow: string; title: string; description: string; fields: ConfigField[] }) {
  const [value, setValue] = useState<Record<string, string | number | boolean | null>>({}); const [initial, setInitial] = useState(value); const [databaseReady, setDatabaseReady] = useState(true); const [notice, setNotice] = useState<string>();
  useEffect(() => { void fetch(`/api/admin/config/${configKey}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) return; const payload = await response.json() as { value: Record<string, string | number | boolean | null>; databaseReady: boolean }; setValue(payload.value); setInitial(payload.value); setDatabaseReady(payload.databaseReady); }); }, [configKey]);
  const save = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`/api/admin/config/${configKey}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const payload = await response.json().catch(() => ({})) as { error?: string }; setNotice(response.ok ? "Saved." : payload.error ?? "Save failed."); if (response.ok) setInitial(value); };
  return <form onSubmit={save}><Header eyebrow={eyebrow} title={title} description={description} />{!databaseReady && <Banner>Connect Supabase before saving. These safe defaults show how Cabi will behave.</Banner>}<div className="mt-7 rounded-[24px] border border-white/[0.065] bg-[#0e0c15] p-5"><div className="grid gap-5 lg:grid-cols-2">{fields.map((field) => <label key={field.key} className={field.kind === "textarea" ? "lg:col-span-2" : ""}><span className="text-xs font-medium text-[#a8a3b3]">{field.label}</span>{field.help && <span className="ml-2 text-[10px] text-[#625d6d]">{field.help}</span>}{field.kind === "textarea" ? <textarea rows={field.key === "systemPrompt" ? 12 : 4} value={String(value[field.key] ?? "")} onChange={(event) => setValue({ ...value, [field.key]: event.target.value })} className="field mt-2 h-auto resize-y py-3 leading-6" /> : field.kind === "boolean" ? <input type="checkbox" checked={Boolean(value[field.key])} onChange={(event) => setValue({ ...value, [field.key]: event.target.checked })} className="ml-3 accent-violet-300" /> : <input type={field.kind === "color" ? "color" : field.kind === "url" ? "url" : "text"} value={String(value[field.key] ?? "")} onChange={(event) => setValue({ ...value, [field.key]: event.target.value })} className={field.kind === "color" ? "mt-2 h-12 w-full cursor-pointer rounded-xl border border-white/[0.08] bg-white/[0.03] p-1" : "field mt-2"} />}</label>)}</div></div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={() => setValue(initial)} className="focus-ring flex h-11 items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 text-sm"><RotateCcw size={15} /> Reset</button><button disabled={!databaseReady} className="focus-ring flex h-11 items-center gap-2 rounded-xl bg-violet-200 px-4 text-sm font-semibold text-[#160f27] disabled:opacity-40"><Save size={15} /> Save</button>{notice && <p role="status" className="text-xs text-violet-200">{notice}</p>}</div></form>;
}
