"use client";

import { Header, Banner } from "@/components/admin/ai-settings-panel";
import { DatabaseZap, ExternalLink, RefreshCcw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";

type Status = { status: string; pages_indexed: number; chunks_indexed: number; created_at: string; completed_at?: string; errors_json?: unknown[] };
type Document = { id: string; title: string; canonical_url: string; fetched_at: string; status: string };
export function KnowledgePanel() {
  const [status, setStatus] = useState<Status | null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [databaseReady, setDatabaseReady] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string>();
  const load = async () => { const response = await fetch("/api/admin/knowledge", { cache: "no-store" }); if (!response.ok) return; const payload = await response.json() as { status: Status | null; documents: Document[]; databaseReady: boolean }; setStatus(payload.status); setDocuments(payload.documents); setDatabaseReady(payload.databaseReady); };
  // Fetching the current index is this effect's external synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const sync = async () => { setBusy(true); setNotice("Syncing public Clank.trade pages…"); const response = await fetch("/api/admin/knowledge/sync", { method: "POST" }); const payload = await response.json().catch(() => ({})) as { pagesIndexed?: number; chunksIndexed?: number; error?: string }; setBusy(false); setNotice(response.ok ? `Indexed ${payload.pagesIndexed} pages and ${payload.chunksIndexed} chunks.` : payload.error ?? "Sync failed."); await load(); };
  const clear = async () => { if (!window.confirm("Clear every indexed page and rebuild the Clank.trade knowledge base now?")) return; setBusy(true); setNotice("Clearing and rebuilding the knowledge base…"); const response = await fetch("/api/admin/knowledge/clear", { method: "DELETE" }); const payload = await response.json().catch(() => ({})) as { pagesIndexed?: number; chunksIndexed?: number; error?: string }; setBusy(false); setNotice(response.ok ? `Rebuilt ${payload.pagesIndexed} pages and ${payload.chunksIndexed} chunks.` : payload.error ?? "Rebuild failed."); await load(); };
  return <div><Header eyebrow="Grounded answers" title="Clank.trade knowledge" description="Cabi indexes only public same-domain pages, respects robots.txt, and treats every page as untrusted reference data." />{!databaseReady && <Banner>Connect Supabase before running a sync.</Banner>}<div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Status", status?.status ?? "Never synced"], ["Pages indexed", status?.pages_indexed ?? 0], ["Chunks indexed", status?.chunks_indexed ?? 0], ["Errors", status?.errors_json?.length ?? 0]].map(([label, value]) => <div key={label} className="rounded-2xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface-1)] p-4"><p className="text-xs text-[var(--cabi-text-muted)]">{label}</p><p className="mt-3 truncate text-xl font-semibold capitalize">{value}</p></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><button disabled={busy || !databaseReady} onClick={() => void sync()} className="focus-ring flex h-11 items-center gap-2 rounded-xl bg-[var(--cabi-primary)] px-4 text-sm font-semibold text-[var(--cabi-on-primary)] disabled:opacity-40"><RefreshCcw size={16} className={busy ? "animate-spin" : ""} /> Sync now</button><button disabled={busy || !databaseReady} onClick={() => void clear()} className="focus-ring flex h-11 items-center gap-2 rounded-xl border border-rose-300/15 bg-rose-300/[0.04] px-4 text-sm text-rose-200 disabled:opacity-40"><Trash2 size={16} /> Clear + rebuild</button>{notice && <p role="status" className="text-xs text-[var(--cabi-primary)]">{notice}</p>}</div><section className="mt-6 overflow-hidden rounded-2xl border border-[var(--cabi-hairline)] bg-[var(--cabi-surface)]"><div className="flex items-center gap-2 border-b border-[var(--cabi-hairline)] px-5 py-4"><DatabaseZap size={16} className="text-[var(--cabi-primary)]" /><h2 className="text-sm font-semibold">Indexed sources</h2></div>{documents.length ? <div className="divide-y divide-white/[0.05]">{documents.map((document) => <div key={document.id} className="flex items-center gap-4 p-4"><div className="min-w-0 flex-1"><p className="truncate text-sm">{document.title}</p><p className="mt-1 truncate text-xs text-[var(--cabi-text-muted)]">{document.canonical_url}</p></div><span className="rounded-full bg-emerald-300/[0.07] px-2 py-1 text-[10px] capitalize text-emerald-300">{document.status}</span><a href={document.canonical_url} target="_blank" rel="noreferrer noopener" className="focus-ring grid h-9 w-9 place-items-center rounded-lg text-[var(--cabi-text-muted)] hover:text-white" aria-label={`Open ${document.title}`}><ExternalLink size={14} /></a></div>)}</div> : <div className="p-10 text-center text-sm text-[var(--cabi-text-muted)]">No indexed pages yet.</div>}</section></div>;
}
