"use client";

import { MiniCabi } from "@/components/cabi/mini-cabi";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { WalletButton } from "@/components/wallet/wallet-button";
import { useWallet } from "@/components/wallet/wallet-provider";
import { ArrowLeft, Download, Moon, Sparkles, Trash2, Volume2, Brain, Database, Info, Lock } from "lucide-react";
import Link from "@/components/prelaunch/preview-link";
import { useCallback, useEffect, useState } from "react";

type Settings = { memory_enabled: boolean; sound_enabled: boolean; animation_mode: "full" | "reduced"; appearance: "dark" | "oled" };
type Memory = { id: string; category: string; content: string; created_at: string };
const defaults: Settings = { memory_enabled: true, sound_enabled: false, animation_mode: "full", appearance: "dark" };

export function SettingsExperience() {
  const wallet = useWallet();
  const [settings, setSettings] = useState(defaults); const [memories, setMemories] = useState<Memory[]>([]); const [notice, setNotice] = useState<string>();
  const load = useCallback(async () => { if (!wallet.authenticated) return; const [settingsResponse, memoryResponse] = await Promise.all([fetch("/api/settings", { cache: "no-store" }), fetch("/api/memories", { cache: "no-store" })]); if (settingsResponse.ok) setSettings(((await settingsResponse.json()) as { settings: Settings }).settings); if (memoryResponse.ok) setMemories(((await memoryResponse.json()) as { memories: Memory[] }).memories); }, [wallet.authenticated]);
  useEffect(() => { if (!wallet.sessionLoaded) return; const timer = window.setTimeout(() => { if (wallet.authenticated) void load(); else { setSettings(defaults); setMemories([]); } }, 0); return () => window.clearTimeout(timer); }, [load, wallet.authenticated, wallet.sessionLoaded]);
  const update = async (patch: Partial<Settings>) => { const previous = settings; setSettings({ ...settings, ...patch }); const response = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); if (!response.ok) { setSettings(previous); setNotice("Settings can be saved after Supabase is connected."); } else setNotice("Saved."); };
  const removeMemory = async (id: string) => { const response = await fetch(`/api/memories/${id}`, { method: "DELETE" }); if (response.ok) setMemories((current) => current.filter((item) => item.id !== id)); };
  const clearMemories = async () => { if (!window.confirm("Forget every saved memory? Your conversations will stay.")) return; const response = await fetch("/api/memories", { method: "DELETE" }); if (response.ok) setMemories([]); };
  const clearData = async () => { if (!window.confirm("Delete all conversations and memories? This cannot be undone.")) return; const response = await fetch("/api/data", { method: "DELETE" }); setNotice(response.ok ? "Your Cabi data was cleared." : "Cabi couldn't clear that data yet."); if (response.ok) setMemories([]); };

  if (wallet.sessionLoaded && !wallet.authenticated) return <main className="cabi-noise min-h-[100dvh] bg-[#07070d] px-4 py-6 text-white sm:px-7 sm:py-8"><div className="mx-auto max-w-5xl"><header className="flex items-center gap-3 sm:gap-4"><Link href="/" className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.03] text-[#a8a3b3] hover:text-white" aria-label="Back to Cabi"><ArrowLeft size={18} /></Link><MiniCabi className="h-12 w-12" /><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold tracking-[-.03em]">Settings</h1><p className="mt-1 truncate text-sm text-[#777180]">Persistent preferences use your wallet identity.</p></div><WalletButton compact /></header><section className="glass mx-auto mt-16 max-w-lg rounded-[28px] p-7 text-center sm:p-9"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl border border-violet-200/15 bg-violet-300/[0.06] text-violet-200"><Lock size={20} /></span><h2 className="mt-5 text-xl font-semibold">Want Cabi to remember your settings?</h2><p className="mt-3 text-sm leading-7 text-[#a8a3b3]">Connect and sign in with an EVM wallet to save memory preferences, appearance, sound, and manage your Cabi data.</p><button onClick={wallet.openConnect} className="focus-ring mt-6 h-11 rounded-xl bg-white px-5 text-sm font-semibold text-[#0b0912]">Connect Wallet</button><p className="mt-3 text-[11px] text-[#706a7d]">Signing is free, costs no gas, and sends no transaction.</p></section></div></main>;

  return <main className="min-h-[100dvh] overflow-x-hidden bg-[#07070d] px-4 py-6 text-white sm:px-7 sm:py-8"><div className="mx-auto max-w-5xl"><header className="flex items-center gap-3 sm:gap-4"><Link href="/" className="focus-ring grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.03] text-[#a8a3b3] hover:text-white" aria-label="Back to Cabi"><ArrowLeft size={18} /></Link><MiniCabi className="h-12 w-12" /><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold tracking-[-.03em]">Settings</h1><p className="mt-1 truncate text-sm text-[#777180]">Make Cabi feel right for you.</p></div><WalletButton compact /></header>
    <Tabs defaultValue="appearance" orientation="vertical" className="mt-8 grid grid-cols-[220px_minmax(0,1fr)] items-start gap-8 max-md:grid-cols-1">
      <TabsList variant="line" className="w-full items-stretch gap-1 rounded-none border-r border-white/[0.07] pr-4 max-md:flex-row max-md:flex-wrap max-md:border-b max-md:border-r-0 max-md:pb-3 max-md:pr-0"><TabsTrigger className="max-md:!w-auto max-md:flex-none" value="appearance"><Moon /> Appearance</TabsTrigger><TabsTrigger className="max-md:!w-auto max-md:flex-none" value="memory"><Brain /> Memory</TabsTrigger><TabsTrigger className="max-md:!w-auto max-md:flex-none" value="sound"><Volume2 /> Sound</TabsTrigger><TabsTrigger className="max-md:!w-auto max-md:flex-none" value="data"><Database /> Data</TabsTrigger><TabsTrigger className="max-md:!w-auto max-md:flex-none" value="about"><Info /> About</TabsTrigger></TabsList>
      <div className="min-w-0">
        <TabsContent value="appearance"><Panel title="Appearance" description="Cabi is designed for the dark. Choose how deep it goes."><SettingRow title="OLED dark" description="Use pure black on compatible screens."><Switch checked={settings.appearance === "oled"} onCheckedChange={(checked) => void update({ appearance: checked ? "oled" : "dark" })} aria-label="OLED dark mode" /></SettingRow><SettingRow title="Reduced animation" description="Keep reactions gentle and remove ambient movement."><Switch checked={settings.animation_mode === "reduced"} onCheckedChange={(checked) => void update({ animation_mode: checked ? "reduced" : "full" })} aria-label="Reduced animation" /></SettingRow></Panel></TabsContent>
        <TabsContent value="memory"><Panel title="Memory" description="Cabi only keeps useful details. You're always in control."><SettingRow title="Enable memory" description="Let Cabi use details you intentionally share in future chats."><Switch checked={settings.memory_enabled} onCheckedChange={(checked) => void update({ memory_enabled: checked })} aria-label="Enable memory" /></SettingRow><div className="mt-5 space-y-2">{memories.length ? memories.map((memory) => <div key={memory.id} className="flex items-start gap-3 rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4"><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-violet-300">{memory.category}</p><p className="mt-1 text-sm leading-6 text-[#d8d4df]">{memory.content}</p></div><button onClick={() => void removeMemory(memory.id)} className="focus-ring grid h-10 w-10 place-items-center rounded-xl text-[#706a7d] hover:bg-rose-300/[0.06] hover:text-rose-300" aria-label="Delete memory"><Trash2 size={16} /></button></div>) : <div className="rounded-2xl border border-dashed border-white/[0.08] p-8 text-center"><MiniCabi className="mx-auto h-12 w-12 opacity-70" decorative /><p className="mt-3 text-sm text-[#8e889b]">Nothing saved yet. Ask Cabi to remember something.</p></div>}</div>{memories.length > 0 && <button onClick={() => void clearMemories()} className="focus-ring mt-4 text-sm text-rose-300 hover:text-rose-200">Clear all memories</button>}</Panel></TabsContent>
        <TabsContent value="sound"><Panel title="Sound" description="Sound stays off until you choose otherwise."><SettingRow title="Subtle UI sounds" description="Small message and milestone sounds. Never music."><Switch checked={settings.sound_enabled} onCheckedChange={(checked) => void update({ sound_enabled: checked })} aria-label="Enable sound" /></SettingRow></Panel></TabsContent>
        <TabsContent value="data"><Panel title="Your data" description="Take a copy or remove what Cabi has stored."><div className="grid gap-3 sm:grid-cols-2"><a href="/api/data/export" className="focus-ring flex items-center gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4 hover:bg-white/[0.045]"><Download size={18} className="text-violet-300" /><div><p className="text-sm font-medium">Export conversations</p><p className="mt-1 text-xs text-[#777180]">Download a JSON copy.</p></div></a><button onClick={() => void clearData()} className="focus-ring flex items-center gap-3 rounded-2xl border border-rose-300/[0.12] bg-rose-300/[0.03] p-4 text-left hover:bg-rose-300/[0.06]"><Trash2 size={18} className="text-rose-300" /><div><p className="text-sm font-medium">Clear all data</p><p className="mt-1 text-xs text-[#777180]">Delete chats and memories.</p></div></button></div></Panel></TabsContent>
        <TabsContent value="about"><Panel title="About Cabi" description="Your Cat Partner Unit."><div className="rounded-[24px] border border-violet-200/[0.10] bg-violet-300/[0.035] p-5"><div className="flex items-center gap-3"><Sparkles className="text-violet-300" size={19} /><p className="font-semibold">Cabi · CPU</p></div><p className="mt-3 max-w-2xl text-sm leading-7 text-[#a8a3b3]">Cabi is a warm, playful digital companion who can remember what matters and explain Clank.trade information from configured sources. She is not a financial adviser, and Clank.trade information is provided for informational purposes.</p></div></Panel></TabsContent>
        {notice && <p role="status" className="mt-4 text-sm text-violet-300">{notice}</p>}
      </div>
    </Tabs></div></main>;
}

function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-semibold tracking-[-.02em]">{title}</h2><p className="mt-1 text-sm text-[#777180]">{description}</p><div className="mt-5 rounded-[24px] border border-white/[0.07] bg-[#0e0c15] p-4 sm:p-5">{children}</div></section>; }
function SettingRow({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="flex min-h-16 items-center gap-4 border-b border-white/[0.06] py-3 last:border-0"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-[#777180]">{description}</p></div>{children}</div>; }
